'use strict';
const $=id=>document.getElementById(id),status=$('status'),t=(vi,en)=>salesPage.text(vi,en);
let products=[],drafts=[],conversations=[],loading=false;
const labels={pending_seller_confirmation:['Chờ xác nhận','Pending confirmation'],confirmed:['Đã xác nhận','Confirmed'],shipped:['Đã gửi hàng','Shipped'],completed:['Hoàn tất','Completed'],cancelled:['Đã hủy','Cancelled']};
const actionLabels={confirm:['Xác nhận đơn','Order confirmed'],ship:['Gửi hàng','Shipped'],complete:['Hoàn tất giao hàng','Delivery completed'],cancel:['Hủy đơn','Cancelled'],paid:['Xác nhận thu tiền','Payment received']};
const errorsEn={'Không tìm thấy sản phẩm.':'Product not found.','Nhập giá hoặc tồn kho cần cập nhật.':'Enter a price or stock update.','Tồn kho không hợp lệ.':'Invalid stock count.','Giá bán không hợp lệ.':'Invalid sale price.','Cần thống nhất phí giao hàng với khách trước khi xác nhận.':'Agree on the shipping fee with the customer before confirming.','Nhập phí giao hàng hợp lệ (0 nếu miễn phí).':'Enter a valid shipping fee (0 for free shipping).','Giá đã thay đổi. Cần khách xác nhận lại và tạo nháp mới.':'The price has changed. Ask the customer to confirm and create a new draft.','Cần kiểm kê đủ tồn kho trước khi xác nhận đơn.':'Verify sufficient stock before confirming this order.','Nhập mã vận đơn hoặc thông tin giao hàng.':'Enter a tracking or delivery reference.','Nhập mã giao dịch hoặc ghi chú xác nhận thu tiền.':'Enter a transaction or receipt reference.','Không thể hủy đơn đã gửi hoặc đã thu tiền; cần xử lý riêng với khách.':'A shipped or paid order requires separate resolution with the customer.','Đơn không còn chờ xác nhận.':'This order is no longer awaiting confirmation.','Chỉ gửi hàng sau khi xác nhận đơn.':'Confirm the order before shipping.','Chỉ hoàn tất sau khi gửi hàng.':'Ship the order before marking delivery complete.','Cần xác nhận đơn trước khi ghi nhận thanh toán.':'Confirm the order before recording payment.','Không tìm thấy đơn.':'Order not found.','Thao tác không hợp lệ.':'Invalid action.'};
const money=value=>Number(value).toLocaleString(salesPage.language==='en'?'en-GB':'vi-VN')+' ₫';
const label=value=>labels[value]?t(...labels[value]):value;
const el=(tag,text,className)=>{const node=document.createElement(tag);if(text!=null)node.textContent=text;if(className)node.className=className;return node;};
function message(text,error=false){status.textContent=text;status.className=error?'error':'';}
async function request(path,options={}){
 const response=await fetch(salesPage.api(path),{credentials:'include',cache:'no-store',...options});const body=await response.json();
 if(!response.ok){if(response.status===401){$('workspace').hidden=true;$('login').hidden=false;products=[];drafts=[];conversations=[];$('drafts').replaceChildren();$('conversations').replaceChildren();}
 throw new Error(salesPage.language==='vi'?(body.error||body.message||'Không xử lý được yêu cầu.'):response.status===401?(path.endsWith('/login')?'Sign-in failed. Check your administrator password.':'Your administrator session expired. Please sign in again.'):(errorsEn[body.error]||`Request failed (HTTP ${response.status}). Check the input and refresh your data.`));}return body;
}
const mutation=(path,method,body)=>request(path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
function pickProduct(){const p=products.find(p=>p.productId===Number($('product').value));if(!p)return;$('price').value=p.price;$('stock').value=p.stock??'';$('productFacts').textContent=p.region+' · '+t(p.priceIsReference?'Giá tham khảo':'Giá người bán',p.priceIsReference?'Reference price':'Seller price')+' · '+t(p.stock===null?'Chưa kiểm kê kho':'Kho: '+p.stock,p.stock===null?'Inventory unverified':'Stock: '+p.stock);}
function renderProducts(){const selected=$('product').value,query=$('productSearch').value.toLocaleLowerCase();$('product').replaceChildren();for(const p of products.filter(p=>(p.name+' '+p.nameEn+' '+p.region).toLocaleLowerCase().includes(query))){const option=el('option',salesPage.language==='en'?p.nameEn:p.name);option.value=p.productId;$('product').append(option);}if([...$('product').options].some(o=>o.value===selected))$('product').value=selected;pickProduct();}
function actionForm(card,draft,action,title,inputSpec,agreement=false){
 const form=el('form'),button=el('button',title,'primary');button.type='submit';
 let input;
 if(inputSpec){const field=el('label',inputSpec.label);input=el('input');input.type=inputSpec.type||'text';input.required=true;if(input.type==='number'){input.min=0;input.max=10000000;input.step=1;input.value=0;}else input.maxLength=120;field.append(input);form.append(field);}
 let agreed;if(agreement){const field=el('label',null,'check');agreed=el('input');agreed.type='checkbox';agreed.required=true;field.append(agreed,el('span',t('Đã thống nhất phí giao với khách','Shipping fee agreed with customer')));form.append(field);}
 form.append(button);form.onsubmit=async event=>{event.preventDefault();button.disabled=true;try{const body={action};if(inputSpec)body[inputSpec.key]=inputSpec.type==='number'?Number(input.value):input.value;if(agreement)body.customerAgreed=agreed.checked;await mutation('/api/admin/sales/drafts/'+encodeURIComponent(draft.id)+'/action','POST',body);await reload();message(t('Đã cập nhật trạng thái đơn.','Order status updated.'));}catch(e){message(e.message,true);}finally{button.disabled=false;}};card.append(form);
}
function renderDrafts(){
 const container=$('drafts');container.replaceChildren();const rows=drafts.filter(d=>$('orderFilter').value==='all'||d.status===$('orderFilter').value).slice().reverse();
 if(!rows.length){container.append(el('p',t('Chưa có đơn trong nhóm này.','No orders in this group.'),'empty'));return;}
 for(const draft of rows){
  const card=el('article',null,'card facts'),header=el('div',null,'order-header');header.append(el('h3',draft.id),el('span',label(draft.status),'badge'));card.append(header);
  card.append(el('p',draft.customer.name+' · '+draft.customer.phone),el('p',draft.customer.address));
  for(const line of draft.lines)card.append(el('p',line.name+' × '+line.quantity+' · '+money(line.unitPrice*line.quantity)));
  card.append(el('p',t('Tạm tính: ','Subtotal: ')+money(draft.subtotal)),el('p',t('Phí giao: ','Shipping: ')+(draft.shippingFee==null?t('Chưa thống nhất','Not agreed'):money(draft.shippingFee))+' · '+t('Tổng: ','Total: ')+(draft.total==null?'—':money(draft.total))),el('p',t('Thanh toán: ','Payment: ')+(draft.paymentStatus==='paid'?t('Người bán đã xác nhận thu tiền','Receipt confirmed by seller'):t('Chưa xác nhận thu tiền','Receipt not confirmed')),'detail'));
  if(draft.trackingNumber)card.append(el('p',t('Thông tin vận chuyển: ','Shipping reference: ')+draft.trackingNumber));
  const actions=el('div',null,'order-actions');
  if(draft.status==='pending_seller_confirmation')actionForm(actions,draft,'confirm',t('Xác nhận & giữ hàng','Confirm & reserve'),{label:t('Phí giao hàng (đồng)','Shipping fee (VND)'),type:'number',key:'shippingFee'},true);
  if(draft.status==='confirmed')actionForm(actions,draft,'ship',t('Xác nhận đã gửi hàng','Mark as shipped'),{label:t('Mã vận đơn / thông tin giao hàng','Tracking / delivery reference'),key:'trackingNumber'});
  if(draft.status==='shipped')actionForm(actions,draft,'complete',t('Xác nhận đã giao xong','Mark as delivered'));
  if(['confirmed','shipped','completed'].includes(draft.status)&&draft.paymentStatus!=='paid')actionForm(actions,draft,'paid',t('Xác nhận đã thu tiền','Confirm payment received'),{label:t('Mã giao dịch / ghi chú thu tiền','Transaction / receipt reference'),key:'paymentReference'});
  if(['pending_seller_confirmation','confirmed'].includes(draft.status)&&draft.paymentStatus!=='paid'){const button=el('button',t('Hủy đơn','Cancel order'),'cancel');button.onclick=async()=>{if(!window.confirm(t('Hủy đơn này và hoàn lại hàng đã giữ?','Cancel this order and release reserved stock?')))return;button.disabled=true;try{await mutation('/api/admin/sales/drafts/'+encodeURIComponent(draft.id)+'/action','POST',{action:'cancel'});await reload();message(t('Đã hủy đơn.','Order cancelled.'));}catch(e){message(e.message,true);}finally{button.disabled=false;}};actions.append(button);}
  card.append(actions);if(draft.history?.length){const details=el('details');details.append(el('summary',t('Lịch sử xử lý','Action history')));for(const h of draft.history)details.append(el('p',(actionLabels[h.action]?t(...actionLabels[h.action]):h.action)+' · '+new Date(h.at).toLocaleString(salesPage.language==='vi'?'vi-VN':'en-GB'),'detail'));card.append(details);}container.append(card);
 }
}
function renderConversations(){
 const container=$('conversations');container.replaceChildren();const filter=$('chatFilter').value,rows=conversations.filter(c=>filter==='all'||(filter==='pending'?c.needsStaff&&c.supportStatus!=='resolved':c.supportStatus==='resolved'));
 if(!rows.length){container.append(el('p',t('Chưa có hội thoại trong nhóm này.','No conversations in this group.'),'empty'));return;}
 for(const row of rows){const card=el('article',null,'card'),details=el('details');details.append(el('summary',new Date(row.updatedAt).toLocaleString(salesPage.language==='vi'?'vi-VN':'en-GB')+' · '+row.id.slice(0,10)+' · '+(row.supportStatus==='resolved'?t('Đã xử lý','Resolved'):row.needsStaff?t('Cần hỗ trợ','Needs support'):t('Tư vấn AI','AI consultation'))));const body=el('div',null,'chat-body');for(const m of row.messages){const bubble=el('div',null,'chat-message '+m.role);bubble.append(el('strong',m.role==='user'?t('Khách hàng','Customer'):'OCOP Copilot'),el('span',m.text));body.append(bubble);}details.append(body);card.append(details);
 if(row.needsStaff&&row.supportStatus!=='resolved'){const button=el('button',t('Đánh dấu đã hỗ trợ khách','Mark support resolved'),'primary');button.onclick=async()=>{button.disabled=true;try{await mutation('/api/admin/sales/conversations/'+row.id+'/resolve','POST',{});await reload();message(t('Đã ghi nhận xử lý hỗ trợ.','Support resolution recorded.'));}catch(e){message(e.message,true);}finally{button.disabled=false;}};card.append(button);}container.append(card);}
}
async function reload(){
 if(loading)return;loading=true;$('reload').disabled=true;
 try{const result=await Promise.all([request('/api/admin/sales/drafts'),request('/api/ai/shop-products'),request('/api/admin/sales/conversations')]);if($('workspace').hidden)return;[drafts,products,conversations]=[result[0].drafts,result[1].products,result[2].conversations];renderProducts();renderDrafts();renderConversations();$('pendingCount').textContent=drafts.filter(d=>d.status==='pending_seller_confirmation').length;$('activeCount').textContent=drafts.filter(d=>['confirmed','shipped'].includes(d.status)).length;$('supportCount').textContent=conversations.filter(c=>c.needsStaff&&c.supportStatus!=='resolved').length;}
 catch(e){message(e.message,true);}finally{loading=false;$('reload').disabled=false;}
}
$('login').onsubmit=async event=>{event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;try{await mutation('/api/admin/audio/login','POST',{password:new FormData(event.target).get('password')});event.target.reset();$('workspace').hidden=false;$('login').hidden=true;message('');await reload();}catch(e){message(e.message,true);}finally{button.disabled=false;}};
$('inventory').onsubmit=async event=>{event.preventDefault();const button=event.target.querySelector('button[type=submit],button.primary');button.disabled=true;try{const body={price:Number($('price').value)};if($('stock').value!=='')body.stock=Number($('stock').value);await mutation('/api/admin/sales/products/'+$('product').value,'PUT',body);await reload();message(t('Đã lưu giá và tồn kho.','Price and inventory saved.'));}catch(e){message(e.message,true);}finally{button.disabled=false;}};
$('reload').onclick=reload;$('product').onchange=pickProduct;$('productSearch').oninput=renderProducts;$('orderFilter').onchange=renderDrafts;$('chatFilter').onchange=renderConversations;
$('logout').onclick=async()=>{try{await request('/api/admin/audio/logout',{method:'POST'});$('workspace').hidden=true;$('login').hidden=false;drafts=[];conversations=[];products=[];$('drafts').replaceChildren();$('conversations').replaceChildren();$('product').replaceChildren();message('');}catch(e){message(e.message,true);}};
function tab(name){for(const key of ['products','orders','chats'])$(key+'Panel').hidden=key!==name;document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.tab===name));}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));tab('products');
document.addEventListener('sales-language',()=>{document.title=t('OCOP • Quản trị người bán','OCOP • Seller workspace');message('');if(!$('workspace').hidden){const price=$('price').value,stock=$('stock').value;renderProducts();$('price').value=price;$('stock').value=stock;renderDrafts();renderConversations();}});
