// data.js - OCOP Specialty Catalog & Configuration
const PRODUCTS = [
  {
    "id": 1,
    "name": "Yến Sào Khánh Hòa Thượng Hạng",
    "region": "Khánh Hòa",
    "category": "gift",
    "stars": 5,
    "price": 2450000,
    "origPrice": 2800000,
    "rating": 5,
    "reviews": 142,
    "tag": "Quà Biếu 5★",
    "img": "images/p1.jpg",
    "desc": "Tổ yến đảo thiên nhiên nguyên chất 100%, bồi bổ cơ thể tăng đề kháng, quà biếu ngoại giao cao cấp."
  },
  {
    "id": 2,
    "name": "Trà Shan Tuyết Cổ Thụ Hà Giang",
    "region": "Hà Giang",
    "category": "tea",
    "stars": 5,
    "price": 680000,
    "origPrice": 750000,
    "rating": 4.9,
    "reviews": 88,
    "tag": "Đặc Sản Hà Giang",
    "img": "images/p2.jpg",
    "desc": "Búp trà cổ thụ trăm năm trên đỉnh cao nguyên đá Hà Giang, hương thơm thanh khiết ngọt hậu đượm đà."
  },
  {
    "id": 3,
    "name": "Trà Đinh Nõn Tân Cương Thái Nguyên",
    "region": "Thái Nguyên",
    "category": "tea",
    "stars": 5,
    "price": 850000,
    "origPrice": 950000,
    "rating": 5,
    "reviews": 210,
    "tag": "Đệ Nhất Danh Trà",
    "img": "images/p3.jpg",
    "desc": "Tuyển chọn từng đọt trà non 1 tôm 2 lá, vị chát dịu nhẹ, hậu ngọt sâu kéo dài chuẩn đệ nhất trà."
  },
  {
    "id": 4,
    "name": "Sâm Ngọc Linh Ngâm Mật Ong Rừng Quảng Nam",
    "region": "Quảng Nam",
    "category": "gift",
    "stars": 5,
    "price": 3200000,
    "origPrice": 3600000,
    "rating": 5,
    "reviews": 75,
    "tag": "Quốc Bảo Việt Nam",
    "img": "images/p4.jpg",
    "desc": "Sâm Ngọc Linh chứa 52 hợp chất saponin ngâm mật ong rừng tự nhiên, phục hồi thể lực toàn diện."
  },
  {
    "id": 5,
    "name": "Nước Mắm Phú Quốc 43° Đạm Ủ Thùng Gỗ",
    "region": "Kiên Giang",
    "category": "spice",
    "stars": 5,
    "price": 220000,
    "origPrice": 250000,
    "rating": 4.9,
    "reviews": 320,
    "tag": "Mắm Truyền Thống",
    "img": "images/p5.jpg",
    "desc": "Ủ chượp thùng gỗ bời lời 12 tháng từ cá cơm than tươi, chuẩn vị đậm đà nguyên bản Phú Quốc."
  },
  {
    "id": 6,
    "name": "Chả Mực Giã Tay Hạ Long",
    "region": "Quảng Ninh",
    "category": "food",
    "stars": 5,
    "price": 490000,
    "origPrice": 550000,
    "rating": 4.9,
    "reviews": 180,
    "tag": "Ẩm Thực Biển",
    "img": "images/p6.jpg",
    "desc": "Mực mai tươi sống giã tay truyền thống Hạ Long, miếng chả sần sật chiên vàng thơm nức mũi."
  },
  {
    "id": 7,
    "name": "Tỏi Đen Lý Sơn Lên Men 60 Ngày",
    "region": "Quảng Ngãi",
    "category": "gift",
    "stars": 5,
    "price": 550000,
    "origPrice": 620000,
    "rating": 4.8,
    "reviews": 95,
    "tag": "Bổ Sức Khỏe",
    "img": "images/p7.jpg",
    "desc": "Lên men tự nhiên 60 ngày từ tỏi một củ đảo Lý Sơn, giàu chống oxy hóa hỗ trợ tim mạch."
  },
  {
    "id": 8,
    "name": "Mật Ong Hoa Cà Phê Tây Nguyên",
    "region": "Gia Lai",
    "category": "food",
    "stars": 4,
    "price": 180000,
    "origPrice": 220000,
    "rating": 4.8,
    "reviews": 260,
    "tag": "Tây Nguyên Tinh Hoa",
    "img": "images/p8.jpg",
    "desc": "Mật ong nguyên chất sánh mịn thơm dịu hương hoa cà phê mùa xuân Tây Nguyên, không pha trộn."
  },
  {
    "id": 9,
    "name": "Kẹo Dừa Bến Tre Nhân Sầu Riêng",
    "region": "Bến Tre",
    "category": "snack",
    "stars": 4,
    "price": 65000,
    "origPrice": 80000,
    "rating": 4.7,
    "reviews": 410,
    "tag": "Đặc Sản Bến Tre",
    "img": "images/p9.jpg",
    "desc": "Nước cốt dừa nguyên chất kết hợp mạch nha và sầu riêng tươi, dẻo thơm ngậy béo không dính răng."
  },
  {
    "id": 10,
    "name": "Bánh Cốm Làng Vòng Hà Nội",
    "region": "Hà Nội",
    "category": "snack",
    "stars": 4,
    "price": 85000,
    "origPrice": 100000,
    "rating": 4.8,
    "reviews": 150,
    "tag": "Hà Thành Quà Quý",
    "img": "images/p10.jpg",
    "desc": "Vỏ cốm xanh dẻo thơm nhân đậu xanh dừa nạo ngào ngạt, chuẩn vị mùa thu Hà Nội làng Vòng."
  },
  {
    "id": 11,
    "name": "Cua Biển Gạch Son Cà Mau",
    "region": "Cà Mau",
    "category": "food",
    "stars": 5,
    "price": 580000,
    "origPrice": 650000,
    "rating": 5,
    "reviews": 195,
    "tag": "Cực Nam Tổ Quốc",
    "img": "images/p11.jpg",
    "desc": "Cua gạch son thịt chắc nịch ngọt đậm đà từ vùng sinh thái rừng ngập mặn Cà Mau thuần túy."
  },
  {
    "id": 12,
    "name": "Trà Hoa Vàng Tam Đảo Vĩnh Phúc",
    "region": "Vĩnh Phúc",
    "category": "tea",
    "stars": 5,
    "price": 1150000,
    "origPrice": 1300000,
    "rating": 4.9,
    "reviews": 64,
    "tag": "Nữ Hoàng Các Loại Trà",
    "img": "images/p12.jpg",
    "desc": "Bông trà hoa vàng sấy lạnh giữ nguyên hoạt chất quý, hạ huyết áp và mát gan thanh lọc hiệu quả."
  },
  {
    "id": 13,
    "name": "Gạo Tám Xoan Hải Hậu Nam Định",
    "region": "Nam Định",
    "category": "food",
    "stars": 4,
    "price": 160000,
    "origPrice": 190000,
    "rating": 4.8,
    "reviews": 110,
    "tag": "Hạt Ngọc Việt",
    "img": "images/p13.jpg",
    "desc": "Hạt gạo thon nhỏ khi nấu chín tỏa hương thơm ngát tự nhiên, cơm dẻo mềm đậm đà tiến vua."
  },
  {
    "id": 14,
    "name": "Hạt Điều Rang Muối Bình Phước Nguyên Vỏ Lụa",
    "region": "Bình Phước",
    "category": "snack",
    "stars": 5,
    "price": 280000,
    "origPrice": 320000,
    "rating": 4.9,
    "reviews": 340,
    "tag": "Nông Sản Xuất Khẩu",
    "img": "images/p14.jpg",
    "desc": "Hạt điều mẩy tròn rang củi nguyên vỏ lụa đỏ, giòn rụm béo bùi vị đậm đà từ vùng đất đỏ Bình Phước."
  },
  {
    "id": 15,
    "name": "Thịt Trâu Gác Bếp Mắc Khén Tây Bắc",
    "region": "Lào Cai",
    "category": "snack",
    "stars": 5,
    "price": 790000,
    "origPrice": 890000,
    "rating": 5,
    "reviews": 270,
    "tag": "Món Ngon Núi Rừng",
    "img": "images/p15.jpg",
    "desc": "Thịt bắp trâu tươi ướp mắc khén hạt dổi hun khói củi bắp, giòn thơm dai xé sợi đậm bản sắc Tây Bắc."
  },
  {
    "id": 16,
    "name": "Đông Trùng Hạ Thảo Đà Lạt Sấy Thăng Hoa",
    "region": "Lâm Đồng",
    "category": "gift",
    "stars": 5,
    "price": 1850000,
    "origPrice": 2100000,
    "rating": 4.9,
    "reviews": 82,
    "tag": "Dược Liệu Cao Cấp",
    "img": "images/p16.jpg",
    "desc": "Nuôi trồng sinh học tại Đà Lạt sấy thăng hoa bảo toàn hàm lượng Cordycepin và adenosine cao."
  },
  {
    "id": 17,
    "name": "Bơ Sáp Đắk Lắk",
    "region": "Đắk Lắk",
    "category": "food",
    "stars": 4,
    "price": 120000,
    "origPrice": 150000,
    "rating": 4.7,
    "reviews": 90,
    "tag": "Trái Cây Tây Nguyên",
    "img": "images/p17.jpg",
    "desc": "Bơ sáp Đắk Lắk chín dẻo quánh vỏ mỏng ruột vàng ươm ngậy béo tự nhiên, không dùng chất bảo quản."
  },
  {
    "id": 18,
    "name": "Mắm Cá Lăng An Giang",
    "region": "An Giang",
    "category": "spice",
    "stars": 4,
    "price": 140000,
    "origPrice": 170000,
    "rating": 4.8,
    "reviews": 130,
    "tag": "Đặc Sản Miền Tây",
    "img": "images/p18.jpg",
    "desc": "Cá lăng ủ thính gạo thơm phức đặc trưng An Giang, chưng thịt và hột vịt ăn với bún rất đậm đà."
  },
  {
    "id": 19,
    "name": "Lạp Xưởng Tôm Cần Đước Long An",
    "region": "Long An",
    "category": "snack",
    "stars": 4,
    "price": 210000,
    "origPrice": 250000,
    "rating": 4.8,
    "reviews": 205,
    "tag": "Truyền Thống Nam Bộ",
    "img": "images/p19.jpg",
    "desc": "Lạp xưởng tươi tôm đất Cần Đước ngọt lịm kết hợp rượu mai quế lộ thơm, đặc sản Nam Bộ chính gốc."
  },
  {
    "id": 20,
    "name": "Vải Thiều Lục Ngạn Bắc Giang Sấy Dẻo",
    "region": "Bắc Giang",
    "category": "snack",
    "stars": 4,
    "price": 130000,
    "origPrice": 160000,
    "rating": 4.9,
    "reviews": 175,
    "tag": "Nông Sản Bắc Giang",
    "img": "images/p20.jpg",
    "desc": "Vải thiều sấy nguyên quả cùi dày ngọt sắc, mùi thơm đặc trưng mùa vải Lục Ngạn chín."
  },
  {
    "id": 21,
    "name": "Cao Chè Vằng Quảng Trị",
    "region": "Quảng Trị",
    "category": "tea",
    "stars": 4,
    "price": 190000,
    "origPrice": 230000,
    "rating": 4.8,
    "reviews": 140,
    "tag": "Sức Khỏe Mẹ & Bé",
    "img": "images/p21.jpg",
    "desc": "Chiết xuất từ lá chè vằng sẻ tự nhiên vùng Quảng Trị, giúp tiêu mỡ, đẹp da và mát gan tiêu độc."
  },
  {
    "id": 22,
    "name": "Tiêu Đen Hữu Cơ Chư Sê Gia Lai",
    "region": "Gia Lai",
    "category": "spice",
    "stars": 4,
    "price": 150000,
    "origPrice": 180000,
    "rating": 4.9,
    "reviews": 115,
    "tag": "Gia Vị Đậm Đà",
    "img": "images/p22.jpg",
    "desc": "Hạt tiêu mẩy mập cay nồng dịu, hương thơm quyến rũ, trồng hữu cơ Chư Sê không thuốc hóa học."
  },
  {
    "id": 23,
    "name": "Nhãn Lồng Hưng Yên",
    "region": "Hưng Yên",
    "category": "food",
    "stars": 4,
    "price": 175000,
    "origPrice": 210000,
    "rating": 4.9,
    "reviews": 230,
    "tag": "Nông Sản Phố Hiến",
    "img": "images/p23.jpg",
    "desc": "Nhãn lồng Hưng Yên chọn khi vừa độ chín, cùi dày vị ngọt thơm tự nhiên, hạt nhỏ đặc sản tiến vua."
  },
  {
    "id": 24,
    "name": "Rượu Cần Men Lá Rừng Tây Nguyên",
    "region": "Đắk Nông",
    "category": "gift",
    "stars": 4,
    "price": 350000,
    "origPrice": 400000,
    "rating": 4.8,
    "reviews": 78,
    "tag": "Văn Hóa Tây Nguyên",
    "img": "images/p24.jpg",
    "desc": "Nếp nương ủ cùng 20 loại lá thuốc rừng Tây Nguyên, vị nồng ấm hài hòa đậm bản sắc văn hóa."
  },
  {
    "id": 25,
    "name": "Bột Rau Má Sấy Lạnh Bình Dương",
    "region": "Bình Dương",
    "category": "tea",
    "stars": 4,
    "price": 230000,
    "origPrice": 270000,
    "rating": 4.7,
    "reviews": 165,
    "tag": "Healthy Life",
    "img": "images/p25.jpg",
    "desc": "Sấy lạnh giữ trọn diệp lục và chất xơ, hỗ trợ giải nhiệt mát gan, giữ dáng khỏe mạnh tự nhiên."
  },
  {
    "id": 26,
    "name": "Mật Táo Đỏ Ninh Thuận",
    "region": "Ninh Thuận",
    "category": "food",
    "stars": 4,
    "price": 210000,
    "origPrice": 250000,
    "rating": 4.8,
    "reviews": 88,
    "tag": "Nắng Gió Ninh Thuận",
    "img": "images/p26.jpg",
    "desc": "Nấu từ táo đỏ Ninh Thuận chín mọng nguyên chất, bổ máu hạ đường huyết giúp ngủ ngon đẹp da."
  },
  {
    "id": 27,
    "name": "Chả Cá Thát Lát Rút Xương Hậu Giang",
    "region": "Hậu Giang",
    "category": "food",
    "stars": 5,
    "price": 310000,
    "origPrice": 360000,
    "rating": 5,
    "reviews": 145,
    "tag": "Đặc Sản Miền Tây",
    "img": "images/p27.jpg",
    "desc": "Cá thát lát tươi rút xương tẩm ướp tiêu gia vị đồng quê, thịt dai giòn sần sật chiên vàng bắt cơm."
  },
  {
    "id": 28,
    "name": "Bánh Pía Sóc Trăng Nhân Sầu Riêng Trứng Muối",
    "region": "Sóc Trăng",
    "category": "snack",
    "stars": 4,
    "price": 115000,
    "origPrice": 140000,
    "rating": 4.8,
    "reviews": 380,
    "tag": "Hương Vị Sóc Trăng",
    "img": "images/p28.jpg",
    "desc": "Vỏ bánh ngàn lớp xốp mịn ôm trọn nhân sầu riêng tươi quyện trứng muối đỏ au béo ngậy."
  },
  {
    "id": 29,
    "name": "Chuối Sấy Dẻo Đồng Nai",
    "region": "Đồng Nai",
    "category": "snack",
    "stars": 4,
    "price": 80000,
    "origPrice": 100000,
    "rating": 4.7,
    "reviews": 120,
    "tag": "Nông Sản Đồng Nai",
    "img": "images/p29.jpg",
    "desc": "Chuối sứ chín cây sấy nhiệt nhẹ dẻo ngọt tự nhiên, không thêm đường không chất bảo quản."
  },
  {
    "id": 30,
    "name": "Dầu Mè Đen Ép Lạnh Thừa Thiên Huế",
    "region": "Thừa Thiên Huế",
    "category": "spice",
    "stars": 4,
    "price": 165000,
    "origPrice": 200000,
    "rating": 4.9,
    "reviews": 92,
    "tag": "Cố Đô Tinh Hoa",
    "img": "images/p30.jpg",
    "desc": "Ép lạnh thủ công từ hạt mè đen thuần chủng Huế, giàu Omega-3 và vitamin E tốt cho tim mạch."
  },
  {
    "id": 31,
    "name": "Nấm Hương Rừng Sa Pa Sấy Khô",
    "region": "Lào Cai",
    "category": "food",
    "stars": 4,
    "price": 240000,
    "origPrice": 280000,
    "rating": 4.8,
    "reviews": 105,
    "tag": "Sương Mù Sa Pa",
    "img": "images/p31.jpg",
    "desc": "Nấm hương rừng Sa Pa chân dài thơm lừng hái tự nhiên, xào nấu hay hầm canh đều ngon đậm đà."
  },
  {
    "id": 32,
    "name": "Trà Shan Tuyết Cổ Thụ Suối Giàng Yên Bái",
    "region": "Yên Bái",
    "category": "tea",
    "stars": 5,
    "price": 920000,
    "origPrice": 1050000,
    "rating": 5,
    "reviews": 160,
    "tag": "Bách Niên Trà",
    "img": "images/p32.jpg",
    "desc": "Búp trà phủ lông tuyết trắng như sương trên cây cổ thụ 100 năm Suối Giàng, nước vàng vị chát dịu."
  },
  {
    "id": 33,
    "name": "Tinh Dầu Sả Chanh Chưng Cất Tuyên Quang",
    "region": "Tuyên Quang",
    "category": "gift",
    "stars": 4,
    "price": 185000,
    "origPrice": 220000,
    "rating": 4.8,
    "reviews": 85,
    "tag": "Thảo Dược Thiên Nhiên",
    "img": "images/p33.jpg",
    "desc": "Chưng cất hơi nước 100% nguyên chất từ sả chanh tươi, khử khuẩn xua muỗi làm ấm phòng hiệu quả."
  },
  {
    "id": 34,
    "name": "Đường Thốt Nốt Bảy Núi An Giang",
    "region": "An Giang",
    "category": "spice",
    "stars": 4,
    "price": 95000,
    "origPrice": 120000,
    "rating": 4.9,
    "reviews": 310,
    "tag": "Đặc Sản Bảy Núi",
    "img": "images/p34.jpg",
    "desc": "Đường tán thủ công từ nhị hoa thốt nốt vùng Bảy Núi, ngọt thanh dịu mát nấu chè kho cá cực ngon."
  },
  {
    "id": 35,
    "name": "Mứt Dâu Tây Đà Lạt Rim Đường Nhẹ",
    "region": "Lâm Đồng",
    "category": "snack",
    "stars": 4,
    "price": 135000,
    "origPrice": 160000,
    "rating": 4.8,
    "reviews": 240,
    "tag": "Phố Hoa Đà Lạt",
    "img": "images/p35.jpg",
    "desc": "Dâu tây thủy canh Đà Lạt rim đường nhẹ giữ trọn vị chua ngọt và màu đỏ tươi tự nhiên."
  },
  {
    "id": 36,
    "name": "Trà Oolong Mộc Châu Sơn La",
    "region": "Sơn La",
    "category": "tea",
    "stars": 5,
    "price": 450000,
    "origPrice": 520000,
    "rating": 4.9,
    "reviews": 130,
    "tag": "Cao Nguyên Mộc Châu",
    "img": "images/p36.jpg",
    "desc": "Viên trà tròn chặt lên men 30% trên cao nguyên Mộc Châu, nước xanh ngọc thơm hương hoa núi mây."
  },
  {
    "id": 37,
    "name": "Khô Cá Lóc Đồng Tháp Mười",
    "region": "Đồng Tháp",
    "category": "food",
    "stars": 4,
    "price": 260000,
    "origPrice": 300000,
    "rating": 4.8,
    "reviews": 190,
    "tag": "Đất Sen Hồng",
    "img": "images/p37.jpg",
    "desc": "Cá lóc đồng ướp ớt tiêu phơi 3 nắng chuẩn vị miền Tây, nướng xé ăn kèm gỏi xoài cực hấp dẫn."
  },
  {
    "id": 38,
    "name": "Rượu Sim Rừng Phú Quốc",
    "region": "Kiên Giang",
    "category": "gift",
    "stars": 4,
    "price": 290000,
    "origPrice": 340000,
    "rating": 4.8,
    "reviews": 110,
    "tag": "Đảo Ngọc Phú Quốc",
    "img": "images/p38.jpg",
    "desc": "Lên men từ quả sim rừng chín mọng đảo Phú Quốc, vị ngọt chát hài hòa trợ tiêu hóa tốt."
  },
  {
    "id": 39,
    "name": "Hạt Mắc Ca Đắk Nông",
    "region": "Đắk Nông",
    "category": "snack",
    "stars": 5,
    "price": 310000,
    "origPrice": 360000,
    "rating": 5,
    "reviews": 290,
    "tag": "Nữ Hoàng Hạt Khô",
    "img": "images/p39.jpg",
    "desc": "Hạt mắc ca nứt vỏ tự nhiên vùng Đắk Nông, nhân trắng ngần béo ngậy, giàu dinh dưỡng tốt cho não."
  },
  {
    "id": 40,
    "name": "Nước Cốt Dừa Ép Lạnh Bến Tre",
    "region": "Bến Tre",
    "category": "food",
    "stars": 4,
    "price": 105000,
    "origPrice": 130000,
    "rating": 4.9,
    "reviews": 350,
    "tag": "Xứ Dừa Tinh Hoa",
    "img": "images/p40.jpg",
    "desc": "Ép lạnh công nghệ hiện đại giữ trọn độ béo ngậy thanh tự nhiên, dùng nấu chè, kho và làm bánh."
  },
  {
    "id": 41,
    "name": "Cà Phê Arabica Cầu Đất Đà Lạt Rang Mộc",
    "region": "Lâm Đồng",
    "category": "food",
    "stars": 4,
    "price": 185000,
    "origPrice": 220000,
    "rating": 4.9,
    "reviews": 178,
    "tag": "Hương Vị Cao Nguyên",
    "img": "images/p41.jpg",
    "desc": "Hạt Arabica tuyển chọn vùng Cầu Đất 1.500m, rang mộc giữ hương thơm dịu và vị chua thanh đặc trưng."
  },
  {
    "id": 42,
    "name": "Chanh Leo Ruột Vàng Đà Lạt",
    "region": "Lâm Đồng",
    "category": "food",
    "stars": 4,
    "price": 120000,
    "origPrice": 145000,
    "rating": 4.8,
    "reviews": 156,
    "tag": "Đặc Sản Đà Lạt",
    "img": "images/p42.jpg",
    "desc": "Chanh leo chín mọng ruột vàng thơm Đà Lạt, vị chua ngọt tự nhiên, pha nước giải khát mát lạnh."
  },
  {
    "id": 43,
    "name": "Tôm Khô Đất Mũi Cà Mau",
    "region": "Cà Mau",
    "category": "food",
    "stars": 4,
    "price": 390000,
    "origPrice": 450000,
    "rating": 4.9,
    "reviews": 112,
    "tag": "Đặc Sản Đất Mũi",
    "img": "images/p43.jpg",
    "desc": "Tôm đất chọn lọc phơi khô truyền thống vùng Đất Mũi, dùng nấu canh kho quẹt và làm mắm ngon."
  },
  {
    "id": 44,
    "name": "Muối Tôm Tây Ninh",
    "region": "Tây Ninh",
    "category": "spice",
    "stars": 4,
    "price": 58000,
    "origPrice": 70000,
    "rating": 4.8,
    "reviews": 205,
    "tag": "Gia Vị Tây Ninh",
    "img": "images/p44.jpg",
    "desc": "Muối rang cùng tôm khô và ớt tươi theo công thức địa phương Tây Ninh, chấm trái cây rất đậm đà."
  },
  {
    "id": 45,
    "name": "Tiêu Đen Phú Quốc",
    "region": "Kiên Giang",
    "category": "spice",
    "stars": 4,
    "price": 125000,
    "origPrice": 150000,
    "rating": 4.9,
    "reviews": 142,
    "tag": "Gia Vị Đảo Ngọc",
    "img": "images/p45.jpg",
    "desc": "Tiêu đen phơi khô tự nhiên trên đảo Phú Quốc, hạt chắc mẩy thơm nồng, xay tươi dùng hằng ngày."
  },
  {
    "id": 46,
    "name": "Bánh Tráng Phơi Sương Tây Ninh",
    "region": "Tây Ninh",
    "category": "snack",
    "stars": 4,
    "price": 68000,
    "origPrice": 82000,
    "rating": 4.8,
    "reviews": 188,
    "tag": "Ẩm Thực Tây Ninh",
    "img": "images/p46.jpg",
    "desc": "Bánh tráng gạo phơi sương đêm mềm dẻo dai, cuốn rau rừng thịt luộc chấm mắm nem rất đặc trưng."
  },
  {
    "id": 47,
    "name": "Trà Sen Hồ Tây Hà Nội",
    "region": "Hà Nội",
    "category": "tea",
    "stars": 5,
    "price": 720000,
    "origPrice": 820000,
    "rating": 5,
    "reviews": 96,
    "tag": "Nghệ Thuật Trà Hà Thành",
    "img": "images/p47.jpg",
    "desc": "Trà xanh Tân Cương ướp gạo sen Hồ Tây thủ công, hương sen thanh tao quyến rũ lưu hương rất lâu."
  },
  {
    "id": 48,
    "name": "Quế Ống Trà Bồng Quảng Ngãi",
    "region": "Quảng Ngãi",
    "category": "spice",
    "stars": 4,
    "price": 145000,
    "origPrice": 175000,
    "rating": 4.8,
    "reviews": 104,
    "tag": "Hương Quế Miền Trung",
    "img": "images/p48.jpg",
    "desc": "Quế Trà Bồng thơm ấm nồng nàn, dùng pha trà, nấu phở, kho thịt hoặc làm quà tặng đặc sản Trung."
  }
];

const CONFIG = {
  BANK_BIN: "970418",
  ACC_NUM: "8808661371",
  ACC_NAME: "HOANG NGUYEN THANH BINH"
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { PRODUCTS, products: PRODUCTS, CONFIG };
}
if (typeof window !== "undefined") {
  window.PRODUCTS = PRODUCTS;
  window.CONFIG = CONFIG;
}
