(function(){
    const TOKEN_KEY='ocop-session-token';
    let token='',ownerId=null,restoring=true,saveTimer=null,saveQueue=Promise.resolve(),pendingCheckout=false;
    const t=(vi,en)=>currentLanguage==='en'?en:vi;
    try{token=localStorage.getItem(TOKEN_KEY)||'';}catch{}
    const snapshot=()=>({cart:cart.map(({id,qty})=>({id,qty})),wishlist:[...wishlist],language:currentLanguage,chatHistory:aiConversationHistory.map(({role,text})=>({role,text}))});
    const getCart=rows=>(rows||[]).map(r=>{const p=products.find(p=>p.id===r.id);return p?{...p,qty:r.qty}:null;}).filter(Boolean);
    function updateUserButton(){const button=document.getElementById('user-btn');button.title=currentUser?t('Tài khoản: ','Account: ')+currentUser.name:t('Đăng nhập / Tài khoản','Sign in / Account');button.setAttribute('aria-label',button.title);}
    function restoreChat(){const box=document.getElementById('ai-chat-messages');box.replaceChildren();for(const m of aiConversationHistory){const el=document.createElement('div');el.className='rounded-xl p-3 text-xs whitespace-pre-wrap break-words '+(m.role==='user'?'bg-emerald-100 ml-6':'bg-white mr-6');el.textContent=m.text;box.append(el);}pendingAIImages=[];lastAIRecommendedProductIds=[];lastAIRecommendationCriteria=null;lastAIComboMarkup=null;activeSearchRecognition=null;renderAIChatImagePreviews();}
    function applyState(state){restoring=true;cart=getCart(state.cart);wishlist=state.wishlist||[];ordersHistory=state.orders||[];aiConversationHistory=(state.chatHistory||[]).slice(-16);currentOrderCode=null;activeVoucher=null;restoreChat();applyLanguage(state.language||currentLanguage);updateCartBadge();updateWishlistBadge();renderCartItems();renderWishlistItems();renderOrdersHistory();updateUserButton();restoring=false;}
    async function api(route,options={},sessionToken=token){const response=await fetch(getAIEndpoint(route),{...options,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:'Bearer '+sessionToken,...options.headers}});const result=await response.json();if(!response.ok){const error=new Error(result.error||t('Không lưu được dữ liệu.','Could not save data.'));error.status=response.status;throw error;}return result;}
    function saveNow(){clearTimeout(saveTimer);if(restoring||!token||!currentUser)return saveQueue;const payload=snapshot(),sessionToken=token;const next=saveQueue.catch(()=>{}).then(()=>api('/api/account/state',{method:'PUT',body:JSON.stringify(payload)},sessionToken));saveQueue=next;return next;}
    function schedule(){if(restoring)return;clearTimeout(saveTimer);if(!currentUser){try{localStorage.setItem('ocop-guest-cart',JSON.stringify({cart:snapshot().cart,wishlist}));}catch{}return;}saveTimer=setTimeout(()=>saveNow().catch(error=>showToast(t('Chưa đồng bộ dữ liệu tài khoản: ','Account data has not synced: ')+error.message,'warning')),250);}
    const ready=new Promise(resolve=>window.addEventListener('DOMContentLoaded',async()=>{try{if(token){const result=await api('/api/auth/me');currentUser=result.user;ownerId=currentUser.id;applyState(result.state);}else{let guest={};try{guest=JSON.parse(localStorage.getItem('ocop-guest-cart')||'{}');}catch{}cart=getCart(guest.cart);wishlist=(guest.wishlist||[]).filter(id=>products.some(p=>p.id===id));updateCartBadge();updateWishlistBadge();renderCartItems();}}catch(error){if(error.status===401){token='';try{localStorage.removeItem(TOKEN_KEY);}catch{}}showToast(t('Vui lòng đăng nhập lại để tải dữ liệu tài khoản.','Please sign in again to load your account data.'),'warning');}finally{restoring=false;updateUserButton();resolve();}}));
    window.accountReady=ready;
    window.acceptAccountLogin=async function(result){await ready;const guest=ownerId?[]:snapshot().cart,guestWishlist=ownerId?[]:[...wishlist];token=result.token;currentUser=result.user;ownerId=currentUser.id;try{localStorage.setItem(TOKEN_KEY,token);localStorage.removeItem('ocop-guest-cart');}catch{}const state=result.state;const merged=new Map((state.cart||[]).map(r=>[r.id,{...r}]));for(const row of guest){const found=merged.get(row.id);merged.set(row.id,{id:row.id,qty:Math.min(99,row.qty+(found?.qty||0))});}applyState({...state,cart:[...merged.values()],wishlist:[...new Set([...(state.wishlist||[]),...guestWishlist])]});await saveNow();if(pendingCheckout){pendingCheckout=false;setTimeout(()=>checkout(),0);}};
    function showLogin(){document.getElementById('cart-drawer').classList.add('hidden');document.getElementById('qr-modal').classList.add('hidden');switchAuthTab('login');document.getElementById('auth-modal').classList.remove('hidden');showToast(t('Vui lòng đăng ký hoặc đăng nhập để thanh toán.','Please create an account or sign in to checkout.'),'info');}
    window.requireAccountCheckout=async function(){await ready;if(!token||!currentUser){pendingCheckout=true;showLogin();return false;}try{await api('/api/auth/me');return true;}catch(error){if(error.status===401){token='';currentUser=null;try{localStorage.removeItem(TOKEN_KEY);}catch{}pendingCheckout=true;showLogin();}else showToast(error.message,'error');return false;}};
    window.createAccountOrder=async function(){await saveNow();const result=await api('/api/orders',{method:'POST',body:JSON.stringify({items:snapshot().cart,voucherCode:activeVoucher?.code||null})});ordersHistory=(await api('/api/auth/me')).state.orders;return result.order;};
    window.reportAccountPayment=async function(id){const result=await api('/api/orders/'+encodeURIComponent(id)+'/payment-reported',{method:'POST',body:'{}'});applyState(result.state);};
    window.logoutAccount=async function(){if(isAIRequestPending){showToast(t('Vui lòng chờ trợ lý trả lời xong trước khi đăng xuất.','Please wait for the assistant to finish before signing out.'),'info');return;}try{await saveNow();await api('/api/auth/logout',{method:'POST',body:'{}'});token='';ownerId=null;currentUser=null;pendingCheckout=false;try{localStorage.removeItem(TOKEN_KEY);localStorage.removeItem('ocop-guest-cart');}catch{}applyState({cart:[],wishlist:[],orders:[],chatHistory:[],language:currentLanguage});document.getElementById('account-panel')?.remove();closeQRModal();showToast(t('Đã đăng xuất. Dữ liệu tài khoản đã lưu.','Signed out. Your account data has been saved.'),'success');}catch(error){showToast(error.message,'error');}};
    const oldAuth=window.toggleAuthModal;
    window.toggleAuthModal=async function(){await ready;if(!currentUser)return oldAuth();document.getElementById('account-panel')?.remove();const panel=document.createElement('div');panel.id='account-panel';panel.className='fixed inset-0 z-[80] flex items-center justify-center p-4 bg-black/60';const card=document.createElement('div');card.className='w-full max-w-sm rounded-3xl bg-white p-6 space-y-4';const heading=document.createElement('h3');heading.className='font-bold text-ocopGreen';heading.textContent=currentUser.name;const detail=document.createElement('p');detail.className='text-sm text-gray-600 whitespace-pre-wrap break-words';detail.textContent=[currentUser.phone,currentUser.email,currentUser.address].filter(Boolean).join('\n');const note=document.createElement('p');note.className='text-xs text-gray-500';note.textContent=t('Giỏ hàng, yêu thích, lịch sử đơn và hội thoại được lưu riêng cho tài khoản này.','Cart, favorites, orders and conversation are saved for this account.');const logout=document.createElement('button');logout.className='w-full rounded-xl bg-ocopGreen text-white p-3 font-bold';logout.textContent=t('Đăng xuất','Sign out');logout.onclick=window.logoutAccount;const close=document.createElement('button');close.className='w-full p-2 text-sm';close.textContent=t('Đóng','Close');close.onclick=()=>panel.remove();card.append(heading,detail,note,logout,close);panel.append(card);panel.addEventListener('click',e=>{if(e.target===panel)panel.remove();});document.body.append(panel);};
    for(const name of ['addToCart','addProductsToCart','updateCartQty','toggleWishlist','sendAIMessage']){const original=window[name];window[name]=async function(...args){await ready;try{return await original(...args);}finally{schedule();}};}
    const oldLanguage=window.applyLanguage;window.applyLanguage=function(...args){const result=oldLanguage(...args);updateUserButton();renderOrdersHistory();schedule();return result;};
    window.addEventListener('pagehide',()=>{if(currentUser&&token&&!restoring)fetch(getAIEndpoint('/api/account/state'),{method:'PUT',keepalive:true,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(snapshot())}).catch(()=>{});});
})();
